import { useState } from 'react'
import { FileText, Clock, Calendar, CheckCircle, X, Download, ArrowLeft, Save } from 'lucide-react'

function ReportDetail({ report, onEdit, onDelete, onBack, isBackendMode = false }) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [showHistoryModal, setShowHistoryModal] = useState(false)
  const [showScheduleModal, setShowScheduleModal] = useState(false)
  const [showGeneratedReport, setShowGeneratedReport] = useState(false)
  const [generatedReportData, setGeneratedReportData] = useState(null)
  const [toast, setToast] = useState(null)
  const [scheduleForm, setScheduleForm] = useState({
    frequency: 'Weekly',
    dayOfWeek: 'Monday',
    time: '09:00',
    recipients: ''
  })

  // Mock history data
  const reportHistory = [
    { id: 1, date: '2026-05-10 14:30', user: 'Alice Smith', status: 'Completed', duration: '2.3s' },
    { id: 2, date: '2026-05-03 09:15', user: 'Bob Johnson', status: 'Completed', duration: '1.8s' },
    { id: 3, date: '2026-04-26 16:45', user: 'Alice Smith', status: 'Completed', duration: '2.1s' },
    { id: 4, date: '2026-04-19 11:20', user: 'Charlie Brown', status: 'Failed', duration: '0.5s' },
    { id: 5, date: '2026-04-12 10:00', user: 'Alice Smith', status: 'Completed', duration: '2.4s' }
  ]

  const showToast = (message, type = 'success') => {
    setToast({ message, type })
    setTimeout(() => setToast(null), 3000)
  }

  const handleGenerateReport = async () => {
    setIsGenerating(true)
    showToast('Generating report...', 'info')
    
    // Simulate API call and generate mock data
    setTimeout(() => {
      const mockData = {
        generatedAt: new Date().toISOString(),
        metrics: {
          totalRecords: Math.floor(Math.random() * 10000) + 1000,
          completionRate: (Math.random() * 30 + 70).toFixed(1) + '%',
          avgProcessingTime: (Math.random() * 5 + 1).toFixed(2) + 's'
        },
        content: `This is a generated report for ${report.name}. The report contains detailed analytics and insights based on current data.`
      }
      setGeneratedReportData(mockData)
      setIsGenerating(false)
      setShowGeneratedReport(true)
      showToast('Report generated successfully!', 'success')
    }, 2000)
  }

  const handleExportPDF = () => {
    showToast('Exporting to PDF...', 'info')
    setTimeout(() => {
      // Create PDF content (text-based for now)
      const pdfContent = `
REPORT: ${report.name}
========================================

Domain: ${report.domain}
Frequency: ${report.frequency}
Compliance Status: ${report.complianceStatus}
Generated: ${new Date().toLocaleString()}

DESCRIPTION:
${report.description}

STAKEHOLDERS:
${report.stakeholders.join(', ')}

========================================
This is a mock PDF export.
For production, integrate with a PDF library like jsPDF.
========================================
`
      
      // Create blob and download
      const blob = new Blob([pdfContent], { type: 'application/pdf' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${report.name.replace(/\s+/g, '_')}_Report.pdf`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
      
      showToast('PDF exported successfully!', 'success')
    }, 1000)
  }

  const handleExportExcel = () => {
    showToast('Exporting to Excel...', 'info')
    setTimeout(() => {
      // Create CSV content (Excel compatible)
      const csvContent = `Report Name,Domain,Frequency,Compliance Status,Description
"${report.name}","${report.domain}","${report.frequency}","${report.complianceStatus}","${report.description}"

Stakeholders
${report.stakeholders.map(s => `"${s}"`).join('\n')}

Generated Date,${new Date().toLocaleString()}
`
      
      // Create blob and download
      const blob = new Blob([csvContent], { type: 'application/vnd.ms-excel' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${report.name.replace(/\s+/g, '_')}_Report.csv`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
      
      showToast('Excel file exported successfully!', 'success')
    }, 1000)
  }

  const handleDownloadHistory = (entry) => {
    showToast(`Downloading report from ${entry.date}...`, 'info')
    setTimeout(() => {
      // Create historical report content
      const reportContent = `
HISTORICAL REPORT: ${report.name}
========================================

Generation Date: ${entry.date}
Generated By: ${entry.user}
Status: ${entry.status}
Duration: ${entry.duration}

========================================
This report was generated on ${entry.date}
Status: ${entry.status}
========================================
`
      
      // Create blob and download
      const blob = new Blob([reportContent], { type: 'application/pdf' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${report.name.replace(/\s+/g, '_')}_${entry.date.replace(/[\s:]/g, '_')}.pdf`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
      
      showToast('Report downloaded successfully!', 'success')
    }, 500)
  }

  const handleSaveGeneratedReport = () => {
    showToast('Saving report...', 'info')
    setTimeout(() => {
      // Save to localStorage for now
      const savedReports = JSON.parse(localStorage.getItem('savedReports') || '[]')
      savedReports.push({
        reportName: report.name,
        data: generatedReportData,
        savedAt: new Date().toISOString()
      })
      localStorage.setItem('savedReports', JSON.stringify(savedReports))
      
      showToast('Report saved successfully!', 'success')
    }, 800)
  }

  const handleDownloadGeneratedReport = () => {
    showToast('Downloading report...', 'info')
    setTimeout(() => {
      // Create detailed generated report content
      const reportContent = `
GENERATED REPORT: ${report.name}
========================================

Generated: ${new Date(generatedReportData.generatedAt).toLocaleString()}

METRICS:
- Total Records: ${generatedReportData.metrics.totalRecords.toLocaleString()}
- Completion Rate: ${generatedReportData.metrics.completionRate}
- Processing Time: ${generatedReportData.metrics.avgProcessingTime}

SUMMARY:
${generatedReportData.content}

SAMPLE DATA:
Metric          | Value        | Status
----------------|--------------|----------
Revenue         | $1,234,567   | Verified
Expenses        | $456,789     | Verified
Net Profit      | $777,778     | Verified

========================================
Report Details:
Domain: ${report.domain}
Frequency: ${report.frequency}
Compliance: ${report.complianceStatus}
========================================
`
      
      // Create blob and download
      const blob = new Blob([reportContent], { type: 'application/pdf' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${report.name.replace(/\s+/g, '_')}_Generated_${new Date().toISOString().split('T')[0]}.pdf`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
      
      showToast('Report downloaded successfully!', 'success')
    }, 800)
  }

  const handleScheduleSubmit = (e) => {
    e.preventDefault()
    showToast(`Report scheduled ${scheduleForm.frequency} at ${scheduleForm.time}`, 'success')
    setShowScheduleModal(false)
  }

  if (!report) {
    return (
      <div className="flex items-center justify-center h-full text-gray-400">
        <div className="text-center">
          <svg className="w-24 h-24 mx-auto mb-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <p className="text-lg font-medium">Select a report from the sidebar</p>
          <p className="text-sm mt-2">Choose from 92 reports across 13 domains</p>
        </div>
      </div>
    )
  }

  return (
    <div className="h-full overflow-y-auto bg-gray-900">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-900 to-blue-800 p-8 border-b border-gray-700">
        <div className="max-w-5xl mx-auto">
          {/* Close/Back Button */}
          {onBack && (
            <button 
              onClick={onBack}
              className="mb-4 flex items-center gap-2 text-blue-200 hover:text-white transition-colors"
            >
              <ArrowLeft size={20} />
              Back to Dashboard
            </button>
          )}
          
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-sm bg-blue-700 text-blue-100 px-3 py-1 rounded">
                  {report.domain}
                </span>
                <span className="text-sm bg-gray-700 text-gray-100 px-3 py-1 rounded">
                  {report.frequency}
                </span>
                <span className={`text-sm px-3 py-1 rounded ${
                  report.complianceStatus === 'Required'
                    ? 'bg-red-900 text-red-200'
                    : 'bg-green-900 text-green-200'
                }`}>
                  {report.complianceStatus}
                </span>
              </div>
              <h1 className="text-3xl font-bold text-white mb-2">{report.name}</h1>
              <p className="text-blue-100">{report.description}</p>
            </div>
            
            <div className="flex gap-2">
              {isBackendMode && onEdit && (
                <button 
                  onClick={() => onEdit(report)}
                  className="bg-yellow-600 hover:bg-yellow-700 px-4 py-2 rounded text-white transition-colors flex items-center gap-2"
                >
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                  Edit
                </button>
              )}
              {isBackendMode && onDelete && (
                <button 
                  onClick={() => onDelete(report)}
                  className="bg-red-600 hover:bg-red-700 px-4 py-2 rounded text-white transition-colors flex items-center gap-2"
                >
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                  Delete
                </button>
              )}
              <button 
                onClick={handleExportPDF}
                className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded text-white transition-colors"
              >
                Export PDF
              </button>
              <button 
                onClick={handleExportExcel}
                className="bg-green-600 hover:bg-green-700 px-4 py-2 rounded text-white transition-colors"
              >
                Export Excel
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-5xl mx-auto p-8">
        {/* Report Details Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          {/* Basic Information */}
          <div className="bg-gray-800 rounded-lg p-6 border border-gray-700">
            <h2 className="text-xl font-semibold text-blue-400 mb-4">Report Information</h2>
            <div className="space-y-3">
              <div>
                <div className="text-sm text-gray-400">Report ID</div>
                <div className="text-white font-mono">#{report.id.toString().padStart(3, '0')}</div>
              </div>
              <div>
                <div className="text-sm text-gray-400">Domain</div>
                <div className="text-white">{report.domain}</div>
              </div>
              <div>
                <div className="text-sm text-gray-400">Frequency</div>
                <div className="text-white">{report.frequency}</div>
              </div>
              <div>
                <div className="text-sm text-gray-400">Compliance Status</div>
                <div className={`font-medium ${
                  report.complianceStatus === 'Required' ? 'text-red-400' : 'text-green-400'
                }`}>
                  {report.complianceStatus}
                </div>
              </div>
            </div>
          </div>

          {/* Stakeholders */}
          <div className="bg-gray-800 rounded-lg p-6 border border-gray-700">
            <h2 className="text-xl font-semibold text-blue-400 mb-4">Stakeholders</h2>
            <div className="flex flex-wrap gap-2">
              {report.stakeholders.map((stakeholder, index) => (
                <span
                  key={index}
                  className="bg-blue-900 text-blue-200 px-3 py-1.5 rounded text-sm"
                >
                  {stakeholder}
                </span>
              ))}
            </div>
            <div className="mt-4 text-sm text-gray-400">
              {report.stakeholders.length} stakeholder{report.stakeholders.length !== 1 ? 's' : ''} involved
            </div>
          </div>
        </div>

        {/* Description Section */}
        <div className="bg-gray-800 rounded-lg p-6 border border-gray-700 mb-8">
          <h2 className="text-xl font-semibold text-blue-400 mb-4">Description</h2>
          <p className="text-gray-300 leading-relaxed">{report.description}</p>
        </div>

        {/* Compliance Requirements */}
        {report.complianceStatus === 'Required' && (
          <div className="bg-red-900/20 border border-red-800 rounded-lg p-6 mb-8">
            <div className="flex items-start gap-3">
              <svg className="w-6 h-6 text-red-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
              <div>
                <h3 className="text-lg font-semibold text-red-400 mb-2">Compliance Required</h3>
                <p className="text-red-200">
                  This report is mandatory and must be submitted according to the {report.frequency.toLowerCase()} schedule.
                  Failure to comply may result in regulatory penalties.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Schedule Information */}
        <div className="bg-gray-800 rounded-lg p-6 border border-gray-700 mb-8">
          <h2 className="text-xl font-semibold text-blue-400 mb-4">Schedule</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <div className="text-sm text-gray-400 mb-1">Frequency</div>
              <div className="text-lg font-semibold text-white">{report.frequency}</div>
            </div>
            <div>
              <div className="text-sm text-gray-400 mb-1">Next Due Date</div>
              <div className="text-lg font-semibold text-yellow-400">Pending</div>
            </div>
            <div>
              <div className="text-sm text-gray-400 mb-1">Last Submission</div>
              <div className="text-lg font-semibold text-green-400">N/A</div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="bg-gray-800 rounded-lg p-6 border border-gray-700">
          <h2 className="text-xl font-semibold text-blue-400 mb-4">Actions</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <button 
              onClick={handleGenerateReport}
              disabled={isGenerating}
              className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-800 disabled:cursor-not-allowed px-6 py-3 rounded text-white transition-colors flex items-center justify-center gap-2"
            >
              {isGenerating ? (
                <>
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                  Generating...
                </>
              ) : (
                <>
                  <FileText size={20} />
                  Generate Report
                </>
              )}
            </button>
            <button 
              onClick={() => setShowHistoryModal(true)}
              className="bg-gray-700 hover:bg-gray-600 px-6 py-3 rounded text-white transition-colors flex items-center justify-center gap-2"
            >
              <Clock size={20} />
              View History
            </button>
            <button 
              onClick={() => setShowScheduleModal(true)}
              className="bg-gray-700 hover:bg-gray-600 px-6 py-3 rounded text-white transition-colors flex items-center justify-center gap-2"
            >
              <Calendar size={20} />
              Schedule Report
            </button>
          </div>
        </div>

        {/* Backend Integration Note */}
        <div className="mt-8 bg-yellow-900/20 border border-yellow-800 rounded-lg p-4">
          <div className="flex items-start gap-3">
            <svg className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <div className="text-sm text-yellow-200">
              <strong>Note:</strong> This is demo data. Connect to backend API at{' '}
              <code className="bg-yellow-900/30 px-1 py-0.5 rounded">/*http://localhost:3000/api/v1</code>*/{import.meta.env.VITE_API_URL || 'http://localhost:3000/api/v1'}
              {' '}to fetch real-time report data and enable full functionality.
            </div>
          </div>
        </div>
      </div>

      {/* Generated Report View Modal */}
      {showGeneratedReport && generatedReportData && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-gray-800 rounded-lg max-w-4xl w-full max-h-[85vh] overflow-hidden border border-gray-700">
            <div className="flex items-center justify-between p-6 border-b border-gray-700 bg-gradient-to-r from-blue-900 to-blue-800">
              <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                <FileText size={24} className="text-blue-300" />
                Generated Report: {report.name}
              </h2>
              <button 
                onClick={() => setShowGeneratedReport(false)}
                className="text-blue-200 hover:text-white transition-colors"
              >
                <X size={24} />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto max-h-[calc(85vh-180px)]">
              {/* Report Metadata */}
              <div className="bg-gray-700 rounded-lg p-4 mb-6 border border-gray-600">
                <div className="grid grid-cols-3 gap-4 text-center">
                  <div>
                    <div className="text-sm text-gray-400 mb-1">Total Records</div>
                    <div className="text-2xl font-bold text-white">{generatedReportData.metrics.totalRecords.toLocaleString()}</div>
                  </div>
                  <div>
                    <div className="text-sm text-gray-400 mb-1">Completion Rate</div>
                    <div className="text-2xl font-bold text-green-400">{generatedReportData.metrics.completionRate}</div>
                  </div>
                  <div>
                    <div className="text-sm text-gray-400 mb-1">Processing Time</div>
                    <div className="text-2xl font-bold text-blue-400">{generatedReportData.metrics.avgProcessingTime}</div>
                  </div>
                </div>
              </div>

              {/* Report Content */}
              <div className="bg-gray-700 rounded-lg p-6 border border-gray-600 mb-6">
                <h3 className="text-xl font-semibold text-blue-400 mb-4">Report Summary</h3>
                <p className="text-gray-300 leading-relaxed mb-4">
                  {generatedReportData.content}
                </p>
                <div className="text-sm text-gray-400">
                  Generated at: {new Date(generatedReportData.generatedAt).toLocaleString()}
                </div>
              </div>

              {/* Sample Data Table */}
              <div className="bg-gray-700 rounded-lg p-6 border border-gray-600">
                <h3 className="text-xl font-semibold text-blue-400 mb-4">Sample Data</h3>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-gray-600">
                        <th className="text-left py-2 px-3 text-gray-300">Metric</th>
                        <th className="text-left py-2 px-3 text-gray-300">Value</th>
                        <th className="text-left py-2 px-3 text-gray-300">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr className="border-b border-gray-600">
                        <td className="py-2 px-3 text-gray-300">Revenue</td>
                        <td className="py-2 px-3 text-white font-medium">$1,234,567</td>
                        <td className="py-2 px-3"><span className="text-green-400">✓ Verified</span></td>
                      </tr>
                      <tr className="border-b border-gray-600">
                        <td className="py-2 px-3 text-gray-300">Expenses</td>
                        <td className="py-2 px-3 text-white font-medium">$456,789</td>
                        <td className="py-2 px-3"><span className="text-green-400">✓ Verified</span></td>
                      </tr>
                      <tr>
                        <td className="py-2 px-3 text-gray-300">Net Profit</td>
                        <td className="py-2 px-3 text-white font-medium">$777,778</td>
                        <td className="py-2 px-3"><span className="text-green-400">✓ Verified</span></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="p-6 border-t border-gray-700 bg-gray-750 flex justify-end gap-3">
              <button 
                onClick={() => setShowGeneratedReport(false)}
                className="px-6 py-2 rounded bg-gray-700 hover:bg-gray-600 text-white transition-colors flex items-center gap-2"
              >
                <X size={18} />
                Close
              </button>
              <button 
                onClick={handleSaveGeneratedReport}
                className="px-6 py-2 rounded bg-green-600 hover:bg-green-700 text-white transition-colors flex items-center gap-2"
              >
                <Save size={18} />
                Save Report
              </button>
              <button 
                onClick={handleDownloadGeneratedReport}
                className="px-6 py-2 rounded bg-blue-600 hover:bg-blue-700 text-white transition-colors flex items-center gap-2"
              >
                <Download size={18} />
                Download
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Toast Notification */}
      {toast && (
        <div className="fixed bottom-4 right-4 z-50 animate-slide-up">
          <div className={`rounded-lg px-6 py-4 shadow-lg flex items-center gap-3 ${
            toast.type === 'success' ? 'bg-green-600' : 
            toast.type === 'error' ? 'bg-red-600' : 
            'bg-blue-600'
          }`}>
            {toast.type === 'success' && <CheckCircle size={20} />}
            <span className="text-white font-medium">{toast.message}</span>
          </div>
        </div>
      )}

      {/* History Modal */}
      {showHistoryModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-gray-800 rounded-lg max-w-3xl w-full max-h-[80vh] overflow-hidden border border-gray-700">
            <div className="flex items-center justify-between p-6 border-b border-gray-700">
              <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                <Clock size={24} className="text-blue-400" />
                Report Generation History
              </h2>
              <button 
                onClick={() => setShowHistoryModal(false)}
                className="text-gray-400 hover:text-white transition-colors"
              >
                <X size={24} />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto max-h-[calc(80vh-100px)]">
              <div className="space-y-3">
                {reportHistory.map((entry) => (
                  <div 
                    key={entry.id}
                    className="bg-gray-700 rounded-lg p-4 border border-gray-600 hover:border-blue-500 transition-colors"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <span className="text-white font-medium">{entry.date}</span>
                          <span className={`px-2 py-1 rounded text-xs font-medium ${
                            entry.status === 'Completed' 
                              ? 'bg-green-900 text-green-200' 
                              : 'bg-red-900 text-red-200'
                          }`}>
                            {entry.status}
                          </span>
                        </div>
                        <div className="text-sm text-gray-400">
                          Generated by <span className="text-blue-400">{entry.user}</span> • Duration: {entry.duration}
                        </div>
                      </div>
                      <button 
                        onClick={() => handleDownloadHistory(entry)}
                        className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded text-white text-sm flex items-center gap-2 transition-colors"
                      >
                        <Download size={16} />
                        Download
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Schedule Modal */}
      {showScheduleModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-gray-800 rounded-lg max-w-2xl w-full border border-gray-700">
            <div className="flex items-center justify-between p-6 border-b border-gray-700">
              <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                <Calendar size={24} className="text-blue-400" />
                Schedule Report Generation
              </h2>
              <button 
                onClick={() => setShowScheduleModal(false)}
                className="text-gray-400 hover:text-white transition-colors"
              >
                <X size={24} />
              </button>
            </div>
            
            <form onSubmit={handleScheduleSubmit} className="p-6">
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Frequency
                  </label>
                  <select 
                    value={scheduleForm.frequency}
                    onChange={(e) => setScheduleForm({...scheduleForm, frequency: e.target.value})}
                    className="w-full bg-gray-700 border border-gray-600 rounded px-4 py-2 text-white focus:outline-none focus:border-blue-500"
                  >
                    <option>Daily</option>
                    <option>Weekly</option>
                    <option>Monthly</option>
                    <option>Quarterly</option>
                  </select>
                </div>

                {scheduleForm.frequency === 'Weekly' && (
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Day of Week
                    </label>
                    <select 
                      value={scheduleForm.dayOfWeek}
                      onChange={(e) => setScheduleForm({...scheduleForm, dayOfWeek: e.target.value})}
                      className="w-full bg-gray-700 border border-gray-600 rounded px-4 py-2 text-white focus:outline-none focus:border-blue-500"
                    >
                      <option>Monday</option>
                      <option>Tuesday</option>
                      <option>Wednesday</option>
                      <option>Thursday</option>
                      <option>Friday</option>
                      <option>Saturday</option>
                      <option>Sunday</option>
                    </select>
                  </div>
                )}

                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Time
                  </label>
                  <input 
                    type="time"
                    value={scheduleForm.time}
                    onChange={(e) => setScheduleForm({...scheduleForm, time: e.target.value})}
                    className="w-full bg-gray-700 border border-gray-600 rounded px-4 py-2 text-white focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Email Recipients (comma-separated)
                  </label>
                  <textarea 
                    value={scheduleForm.recipients}
                    onChange={(e) => setScheduleForm({...scheduleForm, recipients: e.target.value})}
                    placeholder="alice@example.com, bob@example.com"
                    rows={3}
                    className="w-full bg-gray-700 border border-gray-600 rounded px-4 py-2 text-white focus:outline-none focus:border-blue-500"
                  />
                </div>
              </div>

              <div className="flex justify-end gap-3 mt-6">
                <button 
                  type="button"
                  onClick={() => setShowScheduleModal(false)}
                  className="px-6 py-2 rounded bg-gray-700 hover:bg-gray-600 text-white transition-colors"
                >
                  Cancel
                </button>
                <button 
                  type="submit"
                  className="px-6 py-2 rounded bg-blue-600 hover:bg-blue-700 text-white transition-colors"
                >
                  Schedule Report
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

export default ReportDetail
