import { useState, useCallback } from 'react'
import { REPORTS_DATA } from '../data/reportsData'
import {
  Brain, FileText, Download, Copy, CheckCircle,
  RefreshCw, Sparkles, ChevronDown, File
} from 'lucide-react'
import './ReportSummaryGenerator.css'

const DOMAINS = [...new Set(REPORTS_DATA.map(r => r.domain || 'Other').filter(Boolean))].sort()

const SUMMARY_TYPES = [
  { id:'executive',   label:'Executive Brief',      desc:'1-page boardroom summary'              },
  { id:'detailed',    label:'Detailed Analysis',    desc:'Full analysis with recommendations'    },
  { id:'risk',        label:'Risk Report',          desc:'Risk exposure and mitigation plan'     },
  { id:'compliance',  label:'Compliance Status',    desc:'Regulatory compliance overview'        },
  { id:'trend',       label:'Trend Analysis',       desc:'Performance trends over time'          },
]

const COPILOT_PROMPT = (domain, type, count, typeLabel) =>
  `Generate a professional ${typeLabel} for the ${domain} domain of our Enterprise Finance Solution Suite.

Context: The ${domain} domain has ${count} compliance reports. This is part of a ${REPORTS_DATA.length}-report enterprise platform covering 13 business domains.

Requirements:
- Write a complete, board-ready ${typeLabel}
- Include specific sections with headers
- Use professional financial/business language  
- Include specific metrics, percentages, and actionable recommendations
- Structure: Executive Summary, Key Findings, Risk Assessment, Recommendations, Next Steps
- Length: 400-600 words

Generate the complete document now:`

function ReportSummaryGenerator() {
  const [selDomain,   setSelDomain]   = useState('Finance')
  const [selType,     setSelType]     = useState('executive')
  const [summary,     setSummary]     = useState('')
  const [loading,     setLoading]     = useState(false)
  const [copied,      setCopied]      = useState(false)
  const [error,       setError]       = useState('')

  const domainCount = REPORTS_DATA.filter(r => (r.domain || 'Other') === selDomain).length
  const typeObj     = SUMMARY_TYPES.find(t => t.id === selType)

  const generateSummary = useCallback(async () => {
    const key = import.meta.env.VITE_ANTHROPIC_API_KEY
    setLoading(true)
    setSummary('')
    setError('')

    if (!key) {
      // Fallback template when no API key
      setTimeout(() => {
        setSummary(`# ${selDomain} Domain — ${typeObj?.label}
*Enterprise Finance Solution Suite · ${new Date().toLocaleDateString()}*

## Executive Summary
The ${selDomain} domain currently manages ${domainCount} compliance reports within the Enterprise Finance Solution Suite. This domain represents a critical component of the organization's regulatory and operational reporting framework.

## Key Findings
• **Report Coverage:** ${domainCount} active reports spanning Daily, Weekly, Monthly, Quarterly, and Annual frequencies
• **Compliance Rate:** 94.2% — above industry benchmark of 88%
• **Risk Profile:** Medium — ${Math.floor(domainCount * 0.15)} reports flagged for priority review
• **Automation Opportunity:** ${Math.floor(domainCount * 0.35)} reports suitable for full automation

## Risk Assessment
Current risk exposure in the ${selDomain} domain is assessed as **Medium**. Primary risk factors include upcoming regulatory deadline changes and manual processing dependencies in ${Math.floor(domainCount * 0.28)} reports.

## Recommendations
1. Prioritise automation of the ${Math.floor(domainCount * 0.35)} identified reports to reduce manual processing by an estimated 140 hours per quarter
2. Schedule a quarterly review of all ${domainCount} reports to ensure alignment with latest regulatory requirements
3. Implement automated deadline alerts for the ${Math.floor(domainCount * 0.2)} reports with upcoming compliance deadlines
4. Develop escalation protocols for the ${Math.floor(domainCount * 0.05)} reports currently showing overdue status

## Next Steps
- Week 1-2: Stakeholder review of this summary and sign-off
- Month 1: Automation pilot for top 10 identified reports
- Quarter 1: Full implementation of recommended changes
- Quarter 2: Review and measure impact against baseline metrics

---
*Generated by AI Copilot — Enterprise Finance Solution Suite*
*Add VITE_ANTHROPIC_API_KEY for full Claude AI generation*`)
        setLoading(false)
      }, 1200)
      return
    }

    try {
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': key,
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true',
        },
        body: JSON.stringify({
          model: 'claude-sonnet-4-6',
          max_tokens: 1200,
          messages: [{ role:'user', content: COPILOT_PROMPT(selDomain, selType, domainCount, typeObj?.label) }],
        }),
      })
      if (!res.ok) throw new Error(`API error ${res.status}`)
      const data = await res.json()
      setSummary(data.content?.[0]?.text || 'No content generated.')
    } catch (e) {
      setError(`Generation failed: ${e.message}`)
    } finally {
      setLoading(false)
    }
  }, [selDomain, selType, domainCount, typeObj])

  const copyToClipboard = () => {
    navigator.clipboard.writeText(summary).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  const exportAsTxt = () => {
    const blob = new Blob([summary], { type:'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url
    a.download = `${selDomain}-${selType}-summary-${new Date().toISOString().slice(0,10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportAsPDF = () => {
    const printContent = `
      <html><head><title>${selDomain} — ${typeObj?.label}</title>
      <style>
        body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #1a1a2e; line-height: 1.6; }
        h1 { color: #1a1a2e; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; }
        h2 { color: #334155; margin-top: 24px; }
        p  { color: #475569; }
        .meta { color: #64748b; font-size: 0.9em; margin-bottom: 24px; }
      </style></head>
      <body>
        <div class="meta">Enterprise Finance Solution Suite · ${new Date().toLocaleDateString()}</div>
        ${summary.replace(/\n/g,'<br/>').replace(/#{1,3} (.*)/g,'<h2>$1</h2>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>')}
      </body></html>`
    const win = window.open('', '_blank')
    win.document.write(printContent)
    win.document.close()
    win.print()
  }

  // Format markdown-like text
  const formatSummary = (text) =>
    text.split('\n').map((line, i) => {
      if (line.startsWith('# '))  return <h1 key={i} className="rsg-h1">{line.slice(2)}</h1>
      if (line.startsWith('## ')) return <h2 key={i} className="rsg-h2">{line.slice(3)}</h2>
      if (line.startsWith('### '))return <h3 key={i} className="rsg-h3">{line.slice(4)}</h3>
      if (line.startsWith('---')) return <hr key={i} className="rsg-hr"/>
      if (line.startsWith('• ') || line.startsWith('- ')) {
        const content = line.slice(2)
        const parts   = content.split(/\*\*(.*?)\*\*/g)
        return <p key={i} className="rsg-bullet">• {parts.map((p,j) => j%2===1 ? <strong key={j}>{p}</strong> : p)}</p>
      }
      if (line.match(/^\d+\./)) {
        const parts = line.split(/\*\*(.*?)\*\*/g)
        return <p key={i} className="rsg-numbered">{parts.map((p,j) => j%2===1 ? <strong key={j}>{p}</strong> : p)}</p>
      }
      if (!line.trim()) return <br key={i}/>
      const parts = line.split(/\*\*(.*?)\*\*/g)
      return <p key={i} className="rsg-para">{parts.map((p,j) => j%2===1 ? <strong key={j}>{p}</strong> : p)}</p>
    })

  return (
    <div className="rsg-root">
      <div className="rsg-layout">

        {/* Controls */}
        <div className="rsg-controls">
          <div className="rsg-controls-title"><Sparkles size={13}/> Configure Report</div>

          <div className="rsg-form-group">
            <label className="rsg-label">Domain</label>
            <div className="rsg-select-wrap">
              <select className="rsg-select" value={selDomain} onChange={e => setSelDomain(e.target.value)}>
                {DOMAINS.map(d => <option key={d}>{d}</option>)}
              </select>
              <ChevronDown size={13} className="rsg-select-icon"/>
            </div>
            <span className="rsg-domain-meta">{domainCount} reports in this domain</span>
          </div>

          <div className="rsg-form-group">
            <label className="rsg-label">Summary Type</label>
            <div className="rsg-type-list">
              {SUMMARY_TYPES.map(t => (
                <button
                  key={t.id}
                  className={`rsg-type-btn ${selType === t.id ? 'active' : ''}`}
                  onClick={() => setSelType(t.id)}
                >
                  <div>
                    <div className="rsg-type-name">{t.label}</div>
                    <div className="rsg-type-desc">{t.desc}</div>
                  </div>
                  {selType === t.id && <CheckCircle size={13} style={{ color:'#3b82f6' }}/>}
                </button>
              ))}
            </div>
          </div>

          <button className="rsg-generate-btn" onClick={generateSummary} disabled={loading}>
            {loading
              ? <><RefreshCw size={14} style={{ animation:'spin 1s linear infinite' }}/> Generating…</>
              : <><Brain size={14}/> Generate Summary</>
            }
          </button>

          {summary && (
            <div className="rsg-export-group">
              <div className="rsg-export-title">Export As</div>
              <button className="rsg-export-btn" onClick={copyToClipboard}>
                {copied ? <CheckCircle size={12}/> : <Copy size={12}/>}
                {copied ? 'Copied!' : 'Copy Text'}
              </button>
              <button className="rsg-export-btn" onClick={exportAsTxt}>
                <Download size={12}/> Download .txt
              </button>
              <button className="rsg-export-btn primary" onClick={exportAsPDF}>
                <File size={12}/> Export PDF
              </button>
            </div>
          )}
        </div>

        {/* Output */}
        <div className="rsg-output">
          {!summary && !loading && !error && (
            <div className="rsg-placeholder">
              <Brain size={44} style={{ color:'#334155', marginBottom:14 }}/>
              <p>Select a domain and summary type</p>
              <p>then click <strong>Generate Summary</strong></p>
              <p className="rsg-placeholder-hint">Powered by Claude AI · Exports to PDF, TXT</p>
            </div>
          )}

          {loading && (
            <div className="rsg-placeholder">
              <RefreshCw size={28} style={{ color:'#3b82f6', animation:'spin 1s linear infinite', marginBottom:12 }}/>
              <p>Generating <strong>{typeObj?.label}</strong> for <strong>{selDomain}</strong>…</p>
            </div>
          )}

          {error && <div className="rsg-error">{error}</div>}

          {summary && !loading && (
            <div className="rsg-summary-content">
              <div className="rsg-summary-meta">
                <FileText size={13}/>
                <span>{selDomain} · {typeObj?.label}</span>
                <span className="rsg-summary-date">{new Date().toLocaleDateString()}</span>
              </div>
              <div className="rsg-summary-body">{formatSummary(summary)}</div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default ReportSummaryGenerator
